name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, synchronize, reopened ]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout code

      - name: Build and test with Xcode
        run: xcodebuild -project swift-coverage-example.xcodeproj/ -scheme swift-coverage-example -derivedDataPath Build/ -enableCodeCoverage YES clean build test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

      - name: Find Coverage.profdata
        run: find Build/Build/ProfileData -name "Coverage.profdata" -print > coverage_path.txt

      - name: Provide llvm-cov coverage report
        run: |
          coverage_path=$(cat coverage_path.txt)
          if [ -z "$coverage_path" ]; then
            echo "No coverage data found."
            exit 1
          fi
          echo "Coverage data found at: $coverage_path"
          xcrun --run llvm-cov show -instr-profile=$coverage_path \
                Build/Build/Products/Debug/swift-coverage-example.app/Contents/MacOS/swift-coverage-example \
                >Coverage.report

      - uses: SonarSource/sonarqube-scan-action@v4
        name: SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # analysis token associated to your project
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
            projectBaseDir: .
            args: >
              -Dsonar.projectKey=swift-coverage-example
              -Dsonar.projectName=swift-coverage-example
              -Dsonar.swift.coverage.reportPaths=Coverage.report
              -Dsonar.verbose=true