name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, synchronize, reopened ]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build and test with Xcode
        run: xcodebuild -project swift-coverage-example.xcodeproj/ -scheme swift-coverage-example -derivedDataPath Build/ -enableCodeCoverage YES clean build test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

      - name: Find Coverage.profdata
        run: find Build/Build/ProfileData -name "Coverage.profdata" -print > coverage_path.txt

      - name: Provide llvm-cov coverage report
        run: |
          coverage_path=$(cat coverage_path.txt)
          if [ -z "$coverage_path" ]; then
            echo "No coverage data found."
            exit 1
          fi
          echo "Coverage data found at: $coverage_path"
          xcrun --run llvm-cov show -instr-profile=$coverage_path \
                Build/Build/Products/Debug/swift-coverage-example.app/Contents/MacOS/swift-coverage-example \
                >Coverage.report

      - name: Run analysis
        run: | 
          ls -alrt
          cat Coverage.report